import "dotenv/config";
import mongoose from "mongoose";

import ForumPost from "../../backend/models/ForumPost.model.js";
import ShastarInfo from "../../backend/models/ShastarInfo.model.js";
import ResourceMaterial from "../../backend/models/ResourceMaterial.model.js";
import Category from "../../backend/models/Category.model.js";
import User from "../../backend/models/User.model.js";

// Realistic sample data for tests: 5 Forum Posts, 5 Shastars, 5 Resource Materials
// Note: Images are placeholders; focus is on textual content.
const randomImage=[
  "https://res.cloudinary.com/dckgfz6cr/image/upload/v1761935427/shastar/gallery/x8mtmlvao7gxs82za2gt.jpg",
  "https://res.cloudinary.com/dckgfz6cr/image/upload/v1761975253/shastar/main/k5xewxnbsyv7cgzvpnhq.jpg",
  "https://res.cloudinary.com/dckgfz6cr/image/upload/v1761936093/shastar/main/sba7n3u7sfbvpuxokstb.jpg",
  "https://res.cloudinary.com/dckgfz6cr/image/upload/v1761935405/shastar/main/qnh3i9c4n3kmphcyjfqg.png",
  "https://res.cloudinary.com/dckgfz6cr/image/upload/v1761935502/shastar/main/xgtscxy9pyjdov3spbjo.jpg",
  "https://res.cloudinary.com/dckgfz6cr/image/upload/v1761935512/shastar/gallery/rkf0qabl533xg8asv42d.jpg",
  "https://res.cloudinary.com/dckgfz6cr/image/upload/v1759199970/shastar/gallery/admnlnpl5iuerzoblibw.png",
"https://res.cloudinary.com/dckgfz6cr/image/upload/v1759200245/shastar/main/vkqcil4qfhixilwnfoiu.png",



]
const makeDocs = async () => {
  await mongoose.connect(process.env.MONGO_URI);
  console.log(" Connected to MongoDB");
  const user = await User.findOne({ email: "hushedshade@gmail.com" });
  const userId = user._id;
  const sampleForumPosts = [
    {
      title: "The Lost Art of Gatka: Reviving Traditional Sikh Martial Arts",
      author:userId,
      content: "Gatka, the traditional Sikh martial art, has been practiced for centuries but is slowly fading away. The art form combines physical training with spiritual discipline, using weapons like the Kirpan, Chakram, and Talwar.\n\nWhat are your thoughts on preserving this heritage? Have any of you practiced Gatka or seen authentic demonstrations? I'm particularly interested in the philosophical aspects that connect martial training to Sikh principles of courage and righteousness.\n\nLet's discuss how we can bring more attention to this art and ensure it's passed to future generations.",
      category: "martial-arts",
      tags: ["gatka", "sikh-martial-arts", "heritage", "traditional-weapons", "preservation"],
      upvotes: 45,
      downvotes: 2,
      viewCount: 234,
      commentCount: 12,
    },
    {
      title: "Ayurvedic Manuscripts: Hidden Knowledge in Ancient Texts",
      author:userId,
      content: "I recently came across Ayurvedic manuscripts that describe surgical techniques and herbal remedies far ahead of their time. The Sushruta Samhita (c. 600 BCE) contains descriptions of over 300 surgical procedures and 120 instruments, including rhinoplasty techniques.\n\nThere's so much wisdom that could complement modern medicine—especially the holistic approach to health. Anyone else studied these texts or their commentaries?",
      category: "manuscripts",
      tags: ["ayurveda", "ancient-texts", "sushruta", "medical-knowledge", "herbal-remedies"],
      upvotes: 67,
      downvotes: 1,
      viewCount: 456,
      commentCount: 23,
    },
    {
      title: "The Science Behind Vedic Astronomy and Mathematics",
      author:userId,
      content: "The Aryabhatiya (499 CE) calculated the Earth's circumference with remarkable accuracy and proposed Earth's rotation. The decimal system, zero, and early trigonometry appear in Indian sources long before they spread globally.\n\nWhat instruments and observational methods allowed such precision without modern optics? Let's compile resources and reconstructions.",
      category: "ancient-science",
      tags: ["vedic-astronomy", "mathematics", "aryabhata", "ancient-calculations", "zero"],
      upvotes: 89,
      downvotes: 3,
      viewCount: 678,
      commentCount: 31,
    },
    {
      title: "Forgotten Warriors: The Nihang Tradition and Their Weapons",
      author:userId,
      content: "The Nihang Sikhs (Akali) preserved authentic martial traditions, distinctive blue attire, and an arsenal of Khanda, Chakram, Katar, and Barsha. Each weapon carries both practical and spiritual meaning.\n\nAfter training with a Nihang group, I've seen how discipline, meditation, and weapons mastery intertwine. Anyone documenting current training lineages and curriculums?",
      category: "warrior-traditions",
      tags: ["nihang", "sikh-warriors", "traditional-weapons", "martial-discipline", "spiritual-warfare"],
      upvotes: 56,
      downvotes: 0,
      viewCount: 345,
      commentCount: 18,
    },
    {
      title: "Metalworking Excellence: The Wootz Steel Legacy",
      author:userId,
      content: "Wootz steel from southern India (c. 300 BCE) revolutionized metallurgy and led to famed Damascus blades—hard yet flexible. Crucible steel processes used plant carbon sources and precise heat cycles. Sites like Kodumanal yield archaeological evidence.\n\nModern materials science still studies Wootz microstructures. Share papers, reconstructions, and smithing experiments here.",
      category: "ancient-technology",
      tags: ["wootz-steel", "metallurgy", "damascus-steel", "ancient-industry", "blacksmithing"],
      upvotes: 72,
      downvotes: 1,
      viewCount: 523,
      commentCount: 27,
    },
  ];

  const sampleShastars = [
    {
      title: "Khanda - The Double-Edged Sword",
      createdBy:userId,
      alternativeNames: ["Khanda Sahib", "Divine Sword"],
      mainImage: randomImage[Math.floor(Math.random() * randomImage.length)],
      images: [randomImage[Math.floor(Math.random() * randomImage.length)],randomImage[Math.floor(Math.random() * randomImage.length)],randomImage[Math.floor(Math.random() * randomImage.length)]],
      description: "The Khanda symbolizes divine power, justice, and the destruction of evil. A straight, double-edged sword often associated with the Sikh concept of Miri-Piri (temporal and spiritual authority). Traditionally forged with high-quality Wootz steel; the hilt may bear religious motifs. Used historically in 17th–18th century Punjab.",
      type: "weapon",
      subType: "sword",
      material: ["Wootz steel", "Wood", "Brass"],
      weight: "2.5 kg",
      length: "100 cm",
      usage: ["melee", "ceremonial", "spiritual"],
      origin: {
        region: "Punjab region",
        culture: "Sikh",
        timePeriod: "17th–18th Century CE",
        yearEstimated: 1675,
      },
      sources: [{ title: "The Sikh Sword: Weapon and Symbol", author: "P. Singh", link: "", publication: "Journal of Sikh Studies", year: 2019 }],
      category: ["sikh-weapons", "ceremonial", "historical"],
      tags: ["khanda", "sikh-warrior", "double-edged", "spiritual-weapon", "guru-gobind-singh"],
      likes: 156,
      dislikes:0,
      views: 1234,
      commentCount: 28,
    },
    {
      title: "Chakram - The Circular Throwing Weapon",
      createdBy:userId,
      alternativeNames: ["Chakkar", "War Quoit"],
      mainImage: randomImage[Math.floor(Math.random() * randomImage.length)],
      images: [randomImage[Math.floor(Math.random() * randomImage.length)],randomImage[Math.floor(Math.random() * randomImage.length)],randomImage[Math.floor(Math.random() * randomImage.length)]],
      description: "A flat, circular throwing weapon with sharpened outer edge, used by Sikh warriors (notably Nihangs). Typically 10–30 cm diameter, thrown horizontally or vertically with high accuracy. Forged of high-carbon steel and often worn on turbans for rapid deployment.",
      type: "weapon",
      subType: "throwing-weapon",
      material: ["High-carbon steel", "Brass"],
      weight: "0.5 kg",
      length: "20 cm diameter",
      usage: ["ranged", "throwing", "anti-armor"],
      origin: {
        region: "Indian Subcontinent",
        culture: "Sikh, Rajput",
        timePeriod: "16th–19th Century CE",
        yearEstimated: 1600,
      },
      sources: [{ title: "Circular Weapons of Ancient India", author: "R. K. Sharma", link: "", publication: "Arms & Armor Quarterly", year: 2018 }],
      category: ["throwing-weapons", "sikh-weapons", "unique-design"],
      tags: ["chakram", "nihang", "circular-blade", "sikh-martial-arts"],
      likes: 189,
      dislikes:0,
      views: 1567,
      commentCount: 35,
    },
    {
      title: "Ayurvedic Surgical Kit - Sushruta's Instruments",
      createdBy:userId,
      alternativeNames: ["Sushruta Instruments", "Ancient Surgical Tools"],
      mainImage: randomImage[Math.floor(Math.random() * randomImage.length)],
      images: [randomImage[Math.floor(Math.random() * randomImage.length)],randomImage[Math.floor(Math.random() * randomImage.length)],randomImage[Math.floor(Math.random() * randomImage.length)]],
      description: "A reconstructed set of instruments described in Sushruta Samhita (c. 600 BCE): scalpels (Mandalagra), forceps (Vrihimukha), probes (Eshi), and suturing tools (Nadivali). Demonstrates advanced surgical knowledge and ergonomic design in ancient India.",
      type: "tool",
      subType: "medical-instruments",
      material: ["Bronze", "Iron", "Steel"],
      weight: "3 kg (set)",
      length: "5–30 cm",
      usage: ["surgery", "medical", "healing"],
      origin: {
        region: "Indian Subcontinent",
        culture: "Vedic, Classical India",
        timePeriod: "6th Century BCE",
        yearEstimated: 600,
      },
      sources: [{ title: "Sushruta Samhita: Ancient Indian Surgery", author: "K. M. Patel", link: "", publication: "Medical History Journal", year: 2017 }],
      category: ["medical-tools", "ayurveda", "ancient-science"],
      tags: ["sushruta", "surgical-instruments", "ayurveda", "medical-history"],
      likes: 234,
      dislikes:0,
      views: 1890,
      commentCount: 42,
    },
    {
      title: "Katar - The Punch Dagger of Warriors",
      createdBy:userId,
      alternativeNames: ["Push Dagger", "Tekli"],
      mainImage: randomImage[Math.floor(Math.random() * randomImage.length)],
      images: [randomImage[Math.floor(Math.random() * randomImage.length)],randomImage[Math.floor(Math.random() * randomImage.length)],randomImage[Math.floor(Math.random() * randomImage.length)]],
      description: "A distinctive push dagger with an H-shaped grip allowing powerful thrusts from the knuckles. Favored by Rajput and Sikh warriors. Some variants used split-blade mechanisms. Often forged with pattern-welded or Wootz steel and decorated hilts.",
      type: "weapon",
      subType: "dagger",
      material: ["Wootz steel", "Iron"],
      weight: "0.8 kg",
      length: "38 cm",
      usage: ["melee", "close-combat", "armor-piercing"],
      origin: {
        region: "Indian Subcontinent",
        culture: "Rajput, Sikh, Mughal",
        timePeriod: "14th–18th Century CE",
        yearEstimated: 1350,
      },
      sources: [{ title: "Close Combat Weapons of Medieval India", author: "A. K. Singh", link: "", publication: "Journal of Medieval Warfare", year: 2018 }],
      category: ["daggers", "close-combat", "warrior-weapons"],
      tags: ["katar", "punch-dagger", "close-combat", "armor-piercing"],
      likes: 167,
      dislikes:0,
      views: 1456,
      commentCount: 31,
    },
    {
      title: "Vedic Astronomical Instrument - Jantar Mantar",
      createdBy:userId,
      alternativeNames: ["Yantra", "Stone Observatory"],
      mainImage: randomImage[Math.floor(Math.random() * randomImage.length)],
      images: [randomImage[Math.floor(Math.random() * randomImage.length)],randomImage[Math.floor(Math.random() * randomImage.length)],randomImage[Math.floor(Math.random() * randomImage.length)]],
      description: "Stone observatories commissioned by Maharaja Jai Singh II (1724–1735) with large-scale instruments like the Samrat Yantra (giant sundial), Ram Yantra, and Jai Prakash for precise celestial measurements—often within seconds of arc.",
      type: "tool",
      subType: "astronomical-instrument",
      material: ["Stone", "Marble", "Brass fittings"],
      weight: "Several tons",
      length: "Up to 27 m",
      usage: ["astronomy", "timekeeping", "celestial-navigation"],
      origin: {
        region: "North India",
        culture: "Mughal-Maratha synthesis",
        timePeriod: "18th Century CE",
        yearEstimated: 1724,
      },
      sources: [{ title: "Jantar Mantar: Stone Observatories of India", author: "ASI", link: "", publication: "Monumental Heritage Review", year: 2019 }],
      category: ["astronomical-instruments", "ancient-science", "observatories"],
      tags: ["jantar-mantar", "astronomy", "vedic-science", "celestial-observation"],
      likes: 278,
      dislikes:0,
      views: 2134,
      commentCount: 56,
    },
  ];

  const sampleResourceMaterials = [
    {
      title: "The Vedas: Complete Translation and Commentary",
      createdBy:userId,
      mainImage: randomImage[Math.floor(Math.random() * randomImage.length)],
      images: [randomImage[Math.floor(Math.random() * randomImage.length)],randomImage[Math.floor(Math.random() * randomImage.length)],randomImage[Math.floor(Math.random() * randomImage.length)]],
      description: "A modern English rendering with transliteration and commentary for Rig, Yajur, Sama, and Atharva Vedas. Covers ritual context, metrics, linguistic notes, and cross-references. Highlights scientific insights and philosophical foundations of Vedic thought.",
      origin: {
        region: "Indian Subcontinent",
        culture: "Vedic Civilization",
        timePeriod: "1500–1200 BCE",
        yearEstimated: 1300,
      },
      sources: [{ title: "Vedic Knowledge and Modern Science", author: "R. Sharma", link: "", publication: "Journal of Ancient Wisdom", year: 2018 }],
      category: "ancient-texts",
      tags: ["vedas", "sanskrit", "ancient-wisdom", "spiritual-texts", "vedic-knowledge"],
      likes: 445,
      dislikes:0,
      views: 3456,
      commentCount: 67,
    },
    {
      title: "Gatka: The Living Martial Art Tradition",
      createdBy:userId,
      mainImage: randomImage[Math.floor(Math.random() * randomImage.length)],
      images: [randomImage[Math.floor(Math.random() * randomImage.length)],randomImage[Math.floor(Math.random() * randomImage.length)],randomImage[Math.floor(Math.random() * randomImage.length)]],
      description: "A comprehensive manual on Gatka: history, weapon taxonomy (Kirpan, Chakram, Katar, Talwar), footwork, partner drills, forms (yudhvidya), meditation, and ethics. Emphasizes the warrior-spirit framework—courage, discipline, compassion, and seva.",
      origin: {
        region: "Punjab",
        culture: "Sikh Martial Tradition",
        timePeriod: "17th Century CE – Present",
        yearEstimated: 1675,
      },
      sources: [{ title: "Sikh Martial Arts: History and Practice", author: "Gatka Federation of India", link: "", publication: "Martial Arts Heritage Journal", year: 2020 }],
      category: "martial-arts",
      tags: ["gatka", "sikh-martial-arts", "weapon-training", "spiritual-warrior", "nihang-tradition"],
      likes: 323,
      dislikes:0,
      views: 2567,
      commentCount: 48,
    },
    {
      title: "Ancient Indian Metallurgy: The Wootz Steel Revolution",
      createdBy:userId,
      mainImage: randomImage[Math.floor(Math.random() * randomImage.length)],
      images: [randomImage[Math.floor(Math.random() * randomImage.length)],randomImage[Math.floor(Math.random() * randomImage.length)],randomImage[Math.floor(Math.random() * randomImage.length)]],
      description: "Explores crucible steel production, archaeometallurgy of sites in Tamil Nadu/Karnataka, microstructural analysis (cementite, nanotubes), trade diffusion into West Asia, and modern replication attempts. Includes experimental archaeology results.",
      origin: {
        region: "Southern India",
        culture: "Ancient Indian Metallurgy",
        timePeriod: "300 BCE – 18th Century CE",
        yearEstimated: 300,
      },
      sources: [{ title: "Metallurgical Heritage of Ancient India", author: "S. Ranganathan", link: "", publication: "Materials Science History", year: 2019 }],
      category: "ancient-technology",
      tags: ["wootz-steel", "metallurgy", "ancient-industry", "damascus-steel", "blacksmithing"],
      likes: 389,
      dislikes:0,
      views: 2987,
      commentCount: 52,
    },
    {
      title: "Ayurvedic Pharmacopoeia: Ancient Herbal Remedies",
      createdBy:userId,
      mainImage: randomImage[Math.floor(Math.random() * randomImage.length)],
      images: [randomImage[Math.floor(Math.random() * randomImage.length)],randomImage[Math.floor(Math.random() * randomImage.length)],randomImage[Math.floor(Math.random() * randomImage.length)]],
      description: "Documents over 800 medicinal plants with botanical keys, preparation methods (decoctions, taila, churna), therapeutic indications, safety profiles, and conservation notes. Bridges classical formulations with modern pharmacology and clinical evidence.",
      origin: {
        region: "Indian Subcontinent",
        culture: "Ayurvedic Tradition",
        timePeriod: "1000 BCE – Present",
        yearEstimated: 800,
      },
      sources: [{ title: "Ayurvedic Medicine: Ancient Wisdom for Modern Health", author: "V. Kumar", link: "", publication: "Journal of Traditional Medicine", year: 2020 }],
      category: "ayurveda",
      tags: ["ayurveda", "herbal-medicine", "pharmacopoeia", "traditional-healing", "medicinal-plants"],
      likes: 456,
      dislikes:0,
      views: 3789,
      commentCount: 71,
    },
    {
      title: "Sikh Warrior Chronicles: Battles and Strategy",
      createdBy:userId,
      mainImage: randomImage[Math.floor(Math.random() * randomImage.length)],
      images: [randomImage[Math.floor(Math.random() * randomImage.length)],randomImage[Math.floor(Math.random() * randomImage.length)],randomImage[Math.floor(Math.random() * randomImage.length)]],
      description: "Military history from Guru Gobind Singh Ji to the Sikh Empire. Analyzes command structures, logistics, intelligence networks, battlefield ethics (Dharma Yudh), and tactical innovations. Includes maps, battle diagrams, and translated accounts.",
      origin: {
        region: "Punjab and North India",
        culture: "Sikh Military Tradition",
        timePeriod: "1699–1849 CE",
        yearEstimated: 1699,
      },
      sources: [{ title: "Military History of the Sikhs", author: "J. S. Grewal", link: "", publication: "Punjab Historical Society", year: 2017 }],
      category: "military-history",
      tags: ["sikh-warriors", "military-strategy", "battle-history", "guru-gobind-singh", "warrior-ethics"],
      likes: 367,
      dislikes:0,
      views: 2890,
      commentCount: 59,
    },
  ];
  const sampleCategories = [
    { name: "Gatka Training", description: "Traditional Sikh martial art: drills, footwork, forms, and lineages.", categoryType: "ForumPost" },
    { name: "Nihang Tradition", description: "History, codes, practices, and weaponry of the Nihang orders.", categoryType: "ForumPost" },
    { name: "Vedic Astronomy", description: "Observations, instruments, calendars, and computational methods.", categoryType: "ForumPost" },
    { name: "Ayurvedic Manuscripts", description: "Studies on Sushruta, Charaka, Bhela and allied medical treatises.", categoryType: "ForumPost" },
    { name: "Wootz Steel Research", description: "Crucible steel processes, reconstructions, and Damascus blade studies.", categoryType: "ForumPost" },
    { name: "Metallurgy & Smithing", description: "Forging, alloying, heat-treatment, quench/temper techniques.", categoryType: "ForumPost" },
    { name: "Weapon Restoration", description: "Conservation ethics, stabilization, and restoration of arms.", categoryType: "ForumPost" },
    { name: "Battle History", description: "Campaigns, commanders, logistics, tactics across periods.", categoryType: "ForumPost" },
    { name: "Warrior Ethics", description: "Dharma Yudh, conduct codes, and martial philosophy.", categoryType: "ForumPost" },
    { name: "Heritage Preservation", description: "Museums, archives, and community preservation initiatives.", categoryType: "ForumPost" },
    { name: "Ancient Mathematics", description: "Number theory, zero, decimal system, and trigonometry origins.", categoryType: "ForumPost" },
    { name: "Observational Techniques", description: "Pre-modern measurement methods and instrument usage.", categoryType: "ForumPost" },
    { name: "Manuscript Studies", description: "Scripts, paleography, cataloging, and textual criticism.", categoryType: "ForumPost" },
    { name: "Field Experiments", description: "Hands-on reconstructions of historical technologies.", categoryType: "ForumPost" },
    { name: "Arms Collecting", description: "Provenance, identification, and legal considerations.", categoryType: "ForumPost" },

    { name: "Swords", description: "Khanda, Talwar, and other straight/curved blades and typologies.", categoryType: "ShastarInfo" },
    { name: "Daggers", description: "Katar, Bichuwa, and related punch/side dagger forms.", categoryType: "ShastarInfo" },
    { name: "Throwing Weapons", description: "Chakram and other ranged shastars with aerodynamic profiles.", categoryType: "ShastarInfo" },
    { name: "Spears & Polearms", description: "Barsha, bhala, and staff-mounted heads for infantry/cavalry.", categoryType: "ShastarInfo" },
    { name: "Shields & Armor", description: "Dhal, mail-and-plate, helmets, brigandines, and padding.", categoryType: "ShastarInfo" },
    { name: "Ceremonial Weapons", description: "Ritual and symbolic arms used in rites and processions.", categoryType: "ShastarInfo" },
    { name: "Sikh Weapons", description: "Arms associated with Sikh martial traditions and iconography.", categoryType: "ShastarInfo" },
    { name: "Rajput Arms", description: "Regional weapons from Rajput courts and warrior houses.", categoryType: "ShastarInfo" },
    { name: "Mughal Arsenal", description: "Imperial-era arms, workshops, and craftsmanship.", categoryType: "ShastarInfo" },
    { name: "Pattern-Welded Blades", description: "Construction methods and visible steel patterns.", categoryType: "ShastarInfo" },
    { name: "Astronomical Instruments", description: "Stone/metal instruments like Samrat Yantra and Jai Prakash.", categoryType: "ShastarInfo" },
    { name: "Medical Tools", description: "Implements described in Sushruta and surgical traditions.", categoryType: "ShastarInfo" },
    { name: "Training Implements", description: "Practice weapons and gear for conditioning and forms.", categoryType: "ShastarInfo" },
    { name: "Artisan Toolkits", description: "Toolkits of armorers, smiths, and allied craftsmen.", categoryType: "ShastarInfo" },
    { name: "Iconic Artifacts", description: "Objects of high cultural or historical martial significance.", categoryType: "ShastarInfo" },

    { name: "Primary Translations", description: "Readable translations of core Sanskrit, Braj, and Persian sources.", categoryType: "ResourceMaterial" },
    { name: "Critical Commentaries", description: "Scholarly notes and exegesis on primary martial/medical texts.", categoryType: "ResourceMaterial" },
    { name: "Bibliographies", description: "Curated reading lists and reference trails for research.", categoryType: "ResourceMaterial" },
    { name: "Museum Catalogs", description: "Object notes, images, and provenance from institutional collections.", categoryType: "ResourceMaterial" },
    { name: "Field Reports", description: "Ethnographic and archaeological site notes and surveys.", categoryType: "ResourceMaterial" },
    { name: "Research Papers", description: "Peer-reviewed studies on metallurgy, warfare, and texts.", categoryType: "ResourceMaterial" },
    { name: "Instructional Manuals", description: "Guides and structured curricula for training/preservation.", categoryType: "ResourceMaterial" },
    { name: "Archival Guides", description: "Finding aids and navigation for manuscript repositories.", categoryType: "ResourceMaterial" },
    { name: "Conservation Notes", description: "Material care, stabilization, and storage best practices.", categoryType: "ResourceMaterial" },
    { name: "Digital Libraries", description: "Portals hosting scans, datasets, and digital corpora.", categoryType: "ResourceMaterial" },
    { name: "Ancient Texts", description: "Vedas, Upanishads, epics, and ancillary literature.", categoryType: "ResourceMaterial" },
    { name: "Sanskrit Studies", description: "Grammar, lexica, and philology for technical reading.", categoryType: "ResourceMaterial" },
    { name: "Manuscript Conservation", description: "Care of palm-leaf/paper, inks, and environment control.", categoryType: "ResourceMaterial" },
    { name: "Archaeological Surveys", description: "Regional surveys and material culture reports.", categoryType: "ResourceMaterial" },
    { name: "Ethnographic Studies", description: "Living traditions, lineages, and practitioner interviews.", categoryType: "ResourceMaterial" },
    { name: "Pharmacopoeia & Herbals", description: "Materia medica, monographs, and formulation handbooks.", categoryType: "ResourceMaterial" },
    { name: "Historical Maps", description: "Campaign, forts, routes, and trade corridor maps.", categoryType: "ResourceMaterial" },
    { name: "Weapon Typologies", description: "Classification keys and identification guides.", categoryType: "ResourceMaterial" },
    { name: "Armory Inventories", description: "Court/temple armory lists, audits, and ledgers.", categoryType: "ResourceMaterial" },
    { name: "Oral Traditions", description: "Ballads, rahitnamas, and oral histories with martial themes.", categoryType: "ResourceMaterial" },
  ];

  try {
    console.log(` Successfully inserted shastars`);
await ForumPost.insertMany(sampleForumPosts)
await ShastarInfo.insertMany(sampleShastars)
await ResourceMaterial.insertMany(sampleResourceMaterials)
await Category.insertMany(sampleCategories)
    await mongoose.disconnect();
    console.log("  Disconnected from MongoDB");
  } catch (error) {
    console.error("  Error seeding shastars:", error);
    process.exit(1);
  }
};

// Run Seeder
makeDocs();
